#!/usr/bin/env bash

nat_iface=$1
pub_prefix=$2
priv_subnet=$3
nat_map=$4
n_pooling_ips=$5
adm_ips=$6

# Make sure all arguments have been passed, and nat_map and nat_filter are both integers between 0 and 2
if [[ $# -ne 6 || ! ($nat_map =~ ^[0-2]+$ ) ]]; then
    echo """
Usage: ${0} <NAT NETWORK INTERFACE> <PUBLIC NETWORK PREFIX> <PRIVATE SUBNET> <NAT MAPPING TYPE> <AMOUNT OF IPS> <IP ADDRESS LIST>

<NAT MAPPING TYPE> and <NAT FILTERING TYPE> may be one of the following numbers:
    0 - Endpoint-Independent
    1 - Address-Dependent
    2 - Address and Port-Dependent

<AMOUNT OF IPS> specifies the number of IP addresses assigned to each NAT; setting this argument >1 allows NAT IP pooling to be simulated

<IP ADDRESS LIST> is a string of IP addresses separated by a space that may be the destination IP of packets crossing this NAT device (also generated by setup_networks.sh), and is necessary to simulate an Address-Dependent Mapping

This script must be run with root permissions"""
    exit 1
fi

# Create NAT table and chains to configure NAT mapping type
nft add table ip nat
nft add chain nat prerouting { type nat hook prerouting priority -100\; }
nft add chain ip nat postrouting { type nat hook postrouting priority 100\; }

# Dictionary with packet mark key and IP address value, so that we can mark packets to control how their address will be translated
nft add map nat ip_pooling { type mark : ipv4_addr\; }
for ((i=0; i<$n_pooling_ips; i++)); do
    nft add element nat ip_pooling { $i : $pub_prefix.$((254-i)) } # For NAT IPs, host identifiers range from (254 - n_pooling_ips) to 254
done

case $nat_map in
    0) 
        # In EIM the same host always reuses the same mapping, so we set the packet mark by hashing the source IP + UDP/TCP source port
        nft add rule nat prerouting meta l4proto { tcp, udp } ct mark set jhash ip saddr . th sport mod $n_pooling_ips

        nft add rule nat postrouting ip saddr $priv_subnet oif $nat_iface counter snat to ct mark map @ip_pooling persistent;;
    1)
        # In ADM the mapping is reused as long as the destination IP does not change, so we also make the hash depend on the destination IP
        nft add rule nat prerouting meta l4proto { tcp, udp } ct mark set jhash ip saddr . th sport . ip daddr mod $n_pooling_ips

        # Assign a block of 100 ports to each IP in adm_ips
        port_range_start=50000
        port_range_width=100

        # Iterate over each IP
        for ip in $adm_ips; do
            port_range_end=$(($port_range_start + $port_range_width - 1))
            port_range="${port_range_start}-${port_range_end}"
            nft add rule ip nat postrouting ip protocol {tcp, udp} ip saddr $priv_subnet ip daddr $ip oif $nat_iface counter snat to ct mark map @ip_pooling:$port_range persistent
            port_range_start=$(($port_range_end+1))
        done ;;
    2) 
        # In APDM each connection gets a new mapping, so the packet mark can be completely random
        nft add rule nat prerouting ct mark set numgen random mod $n_pooling_ips

        nft add rule nat postrouting ip saddr $priv_subnet oif $nat_iface counter snat to ct mark map @ip_pooling random;;
esac