// Code generated by "stringer -type=EngineState"; DO NOT EDIT.

package toversok

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoSession-0]
	_ = x[CreatingSession-1]
	_ = x[NeedsLogin-2]
	_ = x[Established-3]
	_ = x[StoppingSession-4]
}

const _EngineState_name = "NoSessionCreatingSessionNeedsLoginEstablishedStoppingSession"

var _EngineState_index = [...]uint8{0, 9, 24, 34, 45, 60}

func (i EngineState) String() string {
	if i >= EngineState(len(_EngineState_index)-1) {
		return "EngineState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EngineState_name[_EngineState_index[i]:_EngineState_index[i+1]]
}
