sequenceDiagram
    Client ->> Control: ClientHello
    Control ->> Client: ServerHello
    Client ->> Control: Logon
    critical authenticate
        opt auth url
            Control ->> Client: LogonAuthenticate
        end
        opt device key
            Client ->> Control: LogonDeviceKey
        end
    end
    alt accepted
        Control ->> Client: LogonAccept
    else rejected
        Control ->> Client: LogonReject
    end
